service: data-mesh-explorer
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: tmarinkovic
  stage: dev
  region: eu-west-2

functions:
  getDataMeshBlueprint:
    handler: handler.getDataMeshBlueprint
    events:
      - http:
          path: /
          method: GET
          cors:
            origin: '*'
            headers: '*'

resources:
  Resources:
    DataMeshExplorer:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: data-mesh-explorer
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: DataMeshExplorer
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [ "", [ "arn:aws:s3:::",{ "Ref": "DataMeshExplorer" },"/*" ] ]
